name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
        run: source ~/.nvm/nvm.sh
      - name: Install Node.js
        env:
          NODE_VERSION: 14
        run: nvm use $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: Lint source code with esLint
        run: npm run lint
