name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      - name: source nvm
        run: export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
      - name: Install Node.js
        env:
          NODE_VERSION: 14
        run: nvm use $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: Lint source code with esLint
        run: npm run lint
